inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  NewCops: enable

Layout/LineLength:
  Enabled: false
