name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install libyaml
        run: sudo apt-get update -y && sudo apt-get install -y libyaml-dev

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3

      - name: Lint code
        run: bundle exec rubocop
